### ISSUE TITLE
Why advice root?

### ISSUE THREAD

**Issue by annejan** [neoxharsh/ESP32-GUI-Flasher#1]
> For Linux version, do make sure that you are running the program as sudo, to run it as sudo, navigate to the program directory and enter `sudo ./ESPFlasherGUI`

Is this just for allowing the serial connection to `/dev/ttyUSB` ?

In that case it might be better advice to make sure your user is part of the `dialout` group and/or set appropriate udev rules.

**Comment by neoxharsh** [comment]
Yes that is absolutely correct, but as this is for novice audience, setting up udev rules will be hard, and as the source code is present, the user is not forced to use my executable, they can use the source script. Moreover the only command that get executed under sudo is python.  Thanks for the advice :-) 

Yes it is only to allow access to the USB port. 

I will add the suggestion to make the udev rules in the readme.
