### ISSUE TITLE
COMM port issue?

### ISSUE THREAD

**Issue by ChrisDD11** [neoxharsh/ESP32-GUI-Flasher#2]
Hi guys new to GitsHub but yesterday encountered a problem trying to use the ESPFlasherGUI.  

The attached file is a screenshot of the run I made with the tool and attached .bin files and the error messages I got.

The ESP32 board was attached to COM11 on my laptop no other ports were connected.

Any idea what the problem might be?

![esp_4mb](https://user-images.githubusercontent.com/18310447/28966227-f03bb14a-790c-11e7-953f-afa9ed4f6009.JPG)

**Comment by neoxharsh** [comment]
Try to select COM 11 again, even if it is selected. Then let me know if it works

**Comment by ChrisDD11** [comment]
Thanks for responding. I tried selecting COM11 and got a fatal time out error. Re-tried a few times and same error.
![flash2](https://user-images.githubusercontent.com/18310447/28967730-6e093bea-7914-11e7-8da3-7a710c1f1082.JPG)

**Comment by ChrisDD11** [comment]
Tried 3 more times whilst holding down flash button on board, think it may have worked
![flash3](https://user-images.githubusercontent.com/18310447/28968346-76298c78-7917-11e7-8448-a20dc49854b0.JPG)

**Comment by neoxharsh** [comment]
Which esp32 module are you using? So it worked eventually? 😀

**Comment by ChrisDD11** [comment]
Yes thanks. I have tried looking for output using PUTTY and seems to have the flashed code, need to solder some bits to it now.
![espebay](https://user-images.githubusercontent.com/18310447/28968873-ffc95bd2-7919-11e7-86f6-d4e23f87bddc.JPG)

**Comment by neoxharsh** [comment]
Seems now it is working
