### ISSUE TITLE
ESPIDF update

### ISSUE THREAD

**Issue by PhilColbert** [neoxharsh/ESP32-GUI-Flasher#3]
Hi,

we have been using your flasher for some time now, thanks for writing it, however the new release of ESPIDF doesn't work with the flasher?

Any ideas?

Thanks

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:732
load:0x40078000,len:0
load:0x40078000,len:11640
entry 0x40078444

Hangs here.

Does esptool need updating or ? :) 

Thanks

**Comment by neoxharsh** [comment]
Hi,

Thanks for using my app. As it was just a side project, I have not updated it after pushing it on git. So, let me have a look, and see if I can help you out.

**Comment by PhilColbert** [comment]
Its really useful for people for our project, dead easy way to flash the esp :)

If you could have a look that would be great, I think its just a matter of updating the tools and it will be fine.

If theres anything I can do to help, let me know :)

thanks

**Comment by PhilColbert** [comment]
Hi, is there anything I can do to help, I cant find a decent flasher for people for my project, yours was the only one that was any good ! :)

Thanks

**Comment by neoxharsh** [comment]
Thanks,
 
I worked on it a bit yesterday, today am a bit busy. So, will work on it tomorrow and mostly will get it working.

**Comment by PhilColbert** [comment]
Thanks :) star :)

**Comment by neoxharsh** [comment]
I have tried uploading my compiled micropython firmware using the old version and it seems to upload and run without errors. The error that you are showing is the one after the program is uploaded.

Still I have updated the windows version of the program with the latest esptool. So, check it out and see if it works. Let me know if there are still issues

**Comment by PhilColbert** [comment]
Hi, thanks, but I think the problem must be somewhere else.... the only thing I have changed is the size of the binary and the new IDF version....

This is my flash command line


python /esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port com80 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0xe000 /esp/esp-idf/AirWhere_v5/components/arduino/tools/partitions/boot_app0.bin 0x1000 /esp/esp-idf/AirWhere_v5/build/bootloader/bootloader.bin 0x10000 /esp/esp-idf/AirWhere_v5/build/AirWhere_v5.bin 0x8000 /esp/esp-idf/AirWhere_v5/build/default.bin
esptool.py v2.3.1
Connecting........_
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 753.3 kbit/s)...
Hash of data verified.
Flash params set to 0x0220
Compressed 12480 bytes to 8224...
Wrote 12480 bytes (8224 compressed) at 0x00001000 in 0.2 seconds (effective 504.2 kbit/s)...
Hash of data verified.
Compressed 1591392 bytes to 921136...
Wrote 1591392 bytes (921136 compressed) at 0x00010000 in 18.8 seconds (effective 675.9 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 125...
Wrote 3072 bytes (125 compressed) at 0x00008000 in 0.1 seconds (effective 282.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

The only thing I can see different is the use of the "/esp/esp-idf/AirWhere_v5/components/arduino/tools/partitions/boot_app0.bin " ?

Any ideas ?

Thanks

**Comment by neoxharsh** [comment]
It seems you are using an OTA style partition table.  which partition style are you selecting in menuconfig?

**Comment by neoxharsh** [comment]
Are you able to use it correctly with the command line esptool utility?

**Comment by PhilColbert** [comment]
The command line esptool.py loads it fine and it works ok.

Custom partition to fit BLE on !

# Espressif ESP32 Partition Table,,,,,
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,0x4000,
otadata,data,ota,0xd000,0x2000,
phy_init,data,phy,0xf000,0x1000,
ota_1,app,ota_0,0x10000,1920K,
ota_1,app,ota_1, ,1920K,


I just tried the windows esp32 flashing tool from esp-idf and that does the same as yours.... trying to work out what the difference is...

thanks again

**Comment by PhilColbert** [comment]
Hi, 

Its not your app, i just tested it on an example so it works fine, just trying to work out why mine fails  , thanks

**Comment by PhilColbert** [comment]
For some reason... its just started working, thanks for your help ... very odd!
